version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fitreserve_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitreserve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitreserve_network

  api:
    build: .
    container_name: fitreserve_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: fitreserve
      JWT_SECRET: clave_super_segura_para_jwt_tokens_2024
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    networks:
      - fitreserve_network
    volumes:
      - .:/app
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fitreserve_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fitreserve.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - fitreserve_network

volumes:
  postgres_data:

networks:
  fitreserve_network:
    driver: bridge