services:
  - type: web
    name: fit-clase-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    preDeployCommand: 'node node_modules/typeorm/cli.js migration:run -d dist/src/database/data-source.js'
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
