import { ApiProperty } from '@nestjs/swagger';

export class HealthResponseDto {
  @ApiProperty({ example: 'OK' })
  status!: string;

  @ApiProperty({
    description: 'UTC timestamp generated by the health check',
    example: '2026-08-17T12:00:00.000Z',
  })
  timestamp!: string;
}

export class WelcomeResponseDto {
  @ApiProperty({ description: 'API welcome message' })
  message!: string;
}
